import {Strings} from '../constants'

export const RouteKeys = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  TAB_SCREEN: 'TAB_SCREEN',

  MY_PROFILE: 'MY_PROFILE',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  NOTIFICATIONS_SCREEN: 'NOTIFICATIONS_SCREEN',
  HELP_AND_SUPPORT_SCREEN: 'HELP_AND_SUPPORT_SCREEN',
  EPISODE_DETAILS: 'EPISODE_DETAILS',

  EPISODE_DETAIL_SCREEN: 'EPISODE_DETAIL_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  MESSAGE_SCREEN: 'MESSAGE_SCREEN',
  LOCATION_CONTAINER: 'LOCATION_CONTAINER',
  MAP_SCREEN: 'MAP_SCREEN',
  LIST_VIEW_SCREEN: 'LIST_VIEW_SCREEN',
  LOCATION_DETAILS_SCREEN: 'LOCATION_DETAILS_SCREEN',
  DRAWER_MODAL: 'DRAWER_MODAL',
  ABOUT_US_SCREEN: 'ABOUT_US_SCREEN',
  DONATE_SCREEN: 'DONATE_SCREEN',
  SHOP_STORE_SCREEN: 'SHOP_STORE_SCREEN',
  MEMBERSHIP_SCREEN: 'MEMBERSHIP_SCREEN',
}

export const SCREEN_TITLE = {
  //Home Screen Title
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD_SCREEN: Strings.FORGOT_PASSWORD,
  SIGNUP_SCREEN: Strings.SIGN_UP,
  HOME: Strings.HOME,
  MY_PROFILE: Strings.MY_PROFILE,
  SETTINGS_SCREEN: Strings.SETTINGS,
  //CHAT: Strings.CHAT,
  NOTIFICATIONS_SCREEN: Strings.NOTIFICATIONS,
  EPISODE_DETAIL_SCREEN: 'EPISODE_DETAIL_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  ABOUT_US_SCREEN: 'About Us',
  SHOP_STORE_SCREEN: 'Shop Store',
  DONATE: 'Donate',
}
