import {Strings} from '../constants'

export const RouteKeys = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  HOME_SCREEN: 'HOME_SCREEN',
  TAB_SCREEN: 'TAB_SCREEN',
  MESSAGE_SCREEN: 'MESSAGE_SCREEN',
}

export const SCREEN_TITLE = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  HOME_SCREEN: 'HOME_SCREEN',
  TAB_SCREEN: 'TAB_SCREEN',
  MESSAGE_SCREEN: 'MESSAGE_SCREEN',
}
