export default {
  LOG_IN: 'LOG IN',
  SIGNIN_WITH_YOUREMAIL: 'Sign in with your email/phone number',
  EMAIL_PHONE_NUMBER: 'Email/Phone Number',
  ENTER_EMAIL_PHONE_NUMBER: 'Enter Email/ Phone Number',
  PASSWORD: 'Password',
  ENTER_PASSWORD: 'Enter password',
  ENTER_VALID_PASSWORD_SNACK: 'Password should be of 6 characters atleast.',
  FORGOT_PASSWORD_LOGIN: 'Forgot Password?',
  SIGN_IN: 'Sign In',
  ENTER_AREA_PINCODE: 'Enter Area Pincode',
  ENTER_YOUR_START_LOCATION: 'Enter your from location',
  ENTER_YOUR_DESTINATION_LOCATION: 'Enter your to location',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account? ",
  //search screen
  SEARCH: 'Search',
  SEARCH_LOCATION: 'Search Location',

  SEARCH_TYPE: 'Search Type',
  ROUTE: 'Route',

  //EPISODE DETAILS SCREEN
  SHARE: 'Share',
  SELECT_MEMBERSHIP_PLAN: 'Select a Membership Plan',
  //HOME SCREEN
  LOAD_MORE: 'Load More',
  // FORGOT PASSWORD SCREEN-------------------------------------------
  FORGOT_PASSWORD: 'Forgot Password',
  // SIGN UP SCREEN-------------------------------------------
  SIGN_UP: 'Sign up',
  ENTER_YOUR_DETAILS: 'Enter Your Details',
  FULL_NAME: 'Full Name',
  ENTER_FULL_NAME: 'Enter full name',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter email',
  ENTER_EMAIL_ADDRESS: 'Enter email address',

  ENTER_VALID_EMAIL_SNACK: 'Enter valid Email Address',
  PHONE_NUMBER: 'Phone Number',
  ENTER_PHONENUMBER: 'Enter phone number',

  HOME: 'Home',
  SETTINGS: 'Settings',
  LOGOUT: 'Logout',
  MY_PROFILE: 'My Profile',

  USER_NAME: 'Username',
  EMAIL_ADDRESS: 'Email Address',

  //NOTIFICATIONS SETTINGS
  NOTIFICATIONS_SETTINGS: 'Notifications Settings',
  ALL_NOTIFICATIONS: 'All Notifications',
  NEW_ACTIVITY_NOTIFICATIONS: 'New Activity Notifications',

  NOTIFICATIONS: 'Notifications',

  HERITAGE_TODAY: 'HERITAGE TODAY',
  HELP_AND_SUPPORT: 'Help & Support',
  // SNACKS---------------------------------------------------
  EMAIL_SNACK: 'Email is required',
  VALID_EMAIL_SNACK: 'Enter a valid email',
  PASSWORD_SNACK: 'Password is required',
  VALID_PASSWORD_SNACK: 'Password must have at least 6 characters',
  ADD_SUBJECT: 'Add Subject',
  TYPE_YOUR_MESSAGE: 'Type your message here',
  SEND_TO_ADMIN: 'Send to Admin',
  SUBJECT_IS_REQUIRED: 'Add Subject',
  MESSAGE_IS_REQUIRED: 'Message is required',
  EMAIL_SENT_SUCCESSFULLY: 'Email sent successfully',
  SKIP: 'Skip',
  LOGIN: 'Login',
  MATTHEW49: 'Matthew 4:9',
  SHUBAL_STREANS: 'Shubal Stearns',
  NO_RECORD_FOUND: 'No Records Found',
  MEMBERSHIP_PLAN: 'Membership plan',
  NO_NOTIFICATIONS_FOUND: 'No Notifications Found',
  RESULTS: 'Results',
  ADDRESS: 'Address',
  DIRECTIONS: 'Directions',
  LISTVIEW: 'List View',
  LIGHT: 'Light',
  DARK: 'Dark',
  SLOW: 'Slow',
  FAST: 'Fast',
  SCREEN_MODE: 'Screen Mode',
  REMINDERS: 'Reminders',
  ON: 'On',
  OFF: 'Off',
  AUTO_SCROLL_TEXT: 'Auto Scroll Text',
  SESSION_EXPIRED: 'Session expired !',
  PLEASE_LOGIN_AGAIN: 'Please login again',
  ALERT: 'Alert',
  ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'Are you sure, you want to logout ?',
  CANCEL: 'CANCEL',
  OK: 'OK',
  HIGH: 'High',
  LOW: 'Low',
  AREA: 'Area',
  ACCESS_DIFFICULTY: 'Access Difficulty',
  SEARCH_RADIUS: 'Search Radius',
}
